
--The regional manager wants to analyze total sales generated by each store.

use custumers;
CREATE table store(
    store_id int PRIMARY key,
    store_name VARCHAR(50)
);
CREATE TABLE orders1(
    order_id int PRIMARY key,
    store_id INT,
    order_status INT,
    FOREIGN KEY(store_id) REFERENCES store(store_id)
);

CREATE TABLE order_items(
    item_id int PRIMARY key,
    order_id INT,
    item_discount DECIMAL(4,2),
    item_quantity INT,
    list_price DECIMAL(10,2),
    FOREIGN KEY(order_id) REFERENCES orders1(order_id)

);
INSERT into store VALUES
(1,'palakollu'),
(2,'bhimavaram'),
(3,'eluru');
INSERT into orders1 VALUES
(101,1,3),
(102,3,4),
(103,2,3),
(104,1,4),
(105,2,2);
INSERT into order_items VALUES
(1,101,0.10,2,300),
(2,102,0.05,1,1000),   
(3,104,0.00,3,500),    
(4,103,0.20,2,800),    
(5,105,0.10,1,1200);   
SELECT s.store_name ,SUM(oi.item_quantity*oi.list_price*(1-oi.item_discount)) AS totalsales 
FROM store s INNER JOIN orders1 o ON s.store_id=o.store_id 
INNER join order_items oi ON o.order_id=oi.order_id 
WHERE o.order_status=4 GROUP By s.store_name ORDER by totalsales DESC; 
